repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-case-conflict
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.220
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: [ "--force-exclude" ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
